"""Added new author

Revision ID: 37caabf94ff3
Revises: 
Create Date: 2023-06-29 16:08:14.009844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37caabf94ff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
